modLoader="javafml"
loaderVersion="[34,)"
license="LGPL-3.0"
[[mods]]
modId="janoeo"
version="${file.jarVersion}"
displayName="Just Another Nether/Overworld/End Ores"
authors="AlasDiablo, lIotaMiu, Egame257 and Safyrus"
description='''
Just Another Nether/Overworld/End Ores by AlasDiablo, lIotaMiu, Egame257 and Safyrus
'''
[[dependencies.janoeo]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
