modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0"
[[mods]]
modId="janoeo_foundation"
version="${file.jarVersion}"
displayName="Janoeo Foundation"
logoFile= "janoeo_foundation.png"
authors="AlasDiablo, lIotaMiu and Safyrus"
description='''
Janoeo Project Mod
Mod content:
- Ore generation
'''
[[dependencies.janoeo_foundation]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_foundation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
